config/routes.rb
Rails.application.routes.draw do
  
  root 'articles#index'
  get 'welcome/index'
  resources :sessions, only: [:create]
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'users', to: 'users#index'
  patch '/users/:id', to: 'users#update', as: 'user_update'
  get '/confluence', to: 'confluences#index'
  get '/confluence/space', to: 'confluences#getspacelist'
  get 'confluence/page/:space_id', to: 'confluences#getspacepages', as: 'page'
  get 'confluence/children/:page_id', to: 'confluences#getchildpages', as: 'child'
  get 'confluence/content/:content_id', to: 'confluences#getviewcontent', as: 'pageview'
	
	resources :articles do
    resources :comments
  end

  resources :categories do
  end

	get 'categories/:category_id/articles', to: 'articles#showcategoryarticles', as: 'show_all'
  get 'blog/new', to: 'blog#new'
	post 'blog/new', to: 'blog#create'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :category
	has_many :comments, dependent: :destroy
	validates :title, 
		presence: true, 
		length: { minimum: 5 }, 
		uniqueness: true
end

app/models/bl.rb
class Bl < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles, dependent: :destroy
	validates :name, 
		presence: true, 
		length: { minimum: 5 }, 
		uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :email, uniqueness: true, presence: true
	enum role: [:guest, :editor, :admin]
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
		@category = Category.all
	end

	def edit
		@article = Article.find(params[:id])
		@category = Category.all
	end

	def create
		@article = Article.new(article_params)
		@category = Category.all
	 	if @article.save
	 		redirect_to @article
	 	else
	 		render 'new'
	 		# redirect_to action: "new" 
	 	end
	end

	def update 
		@article = Article.find(params[:id])
		# @category = Category.all
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
	    @article = Article.find(params[:id])
	    authorize @article
	    @article.destroy
	    redirect_to articles_path
  	end

  	def showcategoryarticles
  		@category = Category.find(params[:category_id])
 	end

	private
  		def article_params
    		params.require(:article).permit(:title, :text, :category_id)
  		end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
	def new
	end

	def create
		@blog = Bl.new(param_permission)

		@blog.save
		redirect_to @blog
	end
	private 
		def param_permission
			params.require(:blog).permit(:title, :text)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	#http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
	    @comment = @article.comments.find(params[:id])
	    @comment.destroy
	    redirect_to article_path(@article)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_valid_user!, except: [:destroy]
	
  def new
	end

	def create
		reset_session
		@user = User.find_by(email: session_params[:email])
		
		if @user && @user.authenticate(session_params[:password])
			session[:user_id] = @user.id
      session[:user_email] = @user.email
			flash[:success] = 'welcome'
			redirect_to root_path
		else
			flash[:error] = 'Invalid email/password combination'
			redirect_to login_path
		end
	end

	def destroy
		reset_session
	end

	def session_params
		params.require(:session).permit(:email, :password)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	
    skip_before_action :require_valid_user!

    def index
      @users = User.all
      @enum = User.roles
      authorize @user
    end

  	def new
  		@user = User.new
  	end

  	def create
  		@user = User.new(user_params)

  		if@user.save
  			flash[:success] = 'new user is created'
  			redirect_to login_path
  		else
  			render :new
  		end
  	end

    def update
      @user = User.find(params[:id])
      # @category = Category.all
      # authorize @user
      if @user.update(user_params)
        redirect_to :action => 'index'
      else
        render 'edit'
      end
    end

  	def user_params
  		params.require(:user).permit(:email, :password, :password_confirmation, :role)  		
  	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/confluences_helper.rb
module ConfluencesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<div class="container-form">
  <div class="header">
    <div class="header_title">
      <h4>Edit article</h4>
    </div>
  </div>
  <%= form_for :article, url: article_path(@article), method: :patch do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :class=>'input-box' %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, :class=>'input-box' %>
  </p>
    <p>
    <%= f.label :category_id %>
    <%= f.select :category_id, @category.map{ |c| [c.name, "#{c.id}"] } %>
  </p>
  <p>
    <%= f.submit :class=>"submit" %>
  </p>
  <% end %>
  <%= link_to 'Back', articles_path %>
</div>
 

app/views/articles/index.html.erb
<div class="header">
	<div class="header_title">
		<h1>Articles</h1>
	</div>
</div>
<div class="action_button">
	<button class="btn btn-new btn-primary"><%= link_to 'new article', new_article_path %></button>
	<button class="btn btn-new btn-primary"><%= link_to 'new category', new_category_path %></button>	
</div>

<div class="row article">
	<% @articles.each do |article| %>
		<div class="col-md-3">
			<div class="article__wrapper">
				<div class="article__image">
					<%= link_to image_tag("article_1.jpg", :alt => "article", :class => "article__image" ), article_path(article) %>
				</div>

				<%= link_to article_path(article), :class => "article__link" do%>
					<div class="article_content__wrapper">
						<div class="article__title">
							<strong><%= article.title.capitalize %></strong>
						</div>
						<div class="article__content">
							<%= article.text.truncate(150, separator: " ") %>
						</div>				
					</div>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/articles/new.html.erb
<div class="container-form">
  <div class="header">
    <div class="header_title">
      <h1>Add article</h1>
    </div>
  </div>

  <%= form_for :article, url: articles_path do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, {:class=>'input-box'}%>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, {:class=>'input-box'}%>
  </p>

  <p>
    <%= f.label :category_id %>
    <%= f.select(:category_id, @category.map{ |c| [c.name, "#{c.id}"]}, {:class => 'form-control  '}) %>
  </p>

  <p>
    <%= f.submit 'save', :class => 'form-control submit' %>
  </p>
  <% end %>
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="block-show">

	<h1 clsas="block-show_title"><%= @article.title.capitalize %></h1>
	<div class="block-show_content">
		<%= @article.text %>
	</div>

	<div class="block-show_comments">
		<h5>Comments</h5>
		<% if @article.comments.empty? %>
			<p>no comments added yet</p>
		<% else %>
			<%= render @article.comments %>
		<% end %>
		<h5>Add a comment:</h5>
		<%= render 'comments/form' %>
	</div>

	<%= link_to 'edit', edit_article_path(@article) %> 
	<!-- if destroy action is defined in article policy  -->
	<% if policy(@article).destroy? %> |
		<%= link_to 'delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure to delete?' } %>
	<% end %>
</div>

app/views/articles/showcategoryarticles.html.erb
<h1><%= @category.name.capitalize %></h1>
<div class="row article">
	<% @category.articles.each do |article| %>
		<div class="col-md-3">
			<div class="article__wrapper">
				<div class="article__image">
					<%= link_to image_tag("article_1.jpg", :alt => "article", :class => "article__image" ), article_path(article) %>
				</div>
				<%= link_to article_path(article), :class => "article__link" do%>
					<div class="article_content__wrapper">
						<div class="article__title">
							<strong><%= article.title.capitalize %></strong>
						</div>
						<div class="article__content">
							<%= article.text.truncate(150, separator: " ") %>
						</div>				
					</div>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/comments/_comment.html.erb
<p>
 	<strong>Commenter:</strong>
  	<%= comment.commenter %>
</p>
<p>
	<strong>Comment:</strong>
  	<%= comment.body %>
</p>
<p>
	<%= link_to 'Delete comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_comments.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<div class="container-form-comment">
  <%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :commenter, :class=>'input-box' %>
    </p>
    <p>
      <%= f.label :comment %><br>
      <%= f.text_area :body , :class=>'input-box'%>
    </p>
    <p>
      <%= f.submit 'add comment', :class => 'form-control submit' %>
     <!--  <%= f.submit :class=>"submit  "%> -->
    </p>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html .erb
<%= @users.each do |user| %>
  <% user.email %>
<% end %>

app/views/users/index.html.erb
<div class="content-wrapper">
	<div class="row">
		<div class="col-md-7"><strong>Users</strong></div>
		<div class="col-md-3"><strong>Roles</strong></div>
		<div class="col-md-2"><strong>Action</strong></div>
	</div>
	<!-- <p><%= @enum %></p> -->
	<% @users.each do |user| %>
		<%= form_for :user, url: user_update_path(user), method: :patch do |f| %>
			<div class="row">
				<div class="col-md-7"><%= user.email %></div>
				<div class="col-md-3">
					<%= f.select :role, User.roles.keys.to_a, :selected => user.role %>
					<%= user.role %>
				</div>
				<div class="col-md-2"><%= f.submit :class=>"submit form-control" %></div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="container-form">
  <h1>Sign Up</h1>
  <p>Create a new account using the form below.  All fields are required.</p>

  <% if @user.errors.any? %>
    	<div class='alert alert-danger'>
      	<p>Please correct the following errors:</p>
      	<ul>
  		    <% @user.errors.full_messages.each do |msg| %>
  		    	<li><%= msg %></li>
  		    <% end %>
  	    </ul>
    	</div>
  <% end %>

  <%= form_for @user do |f| %>
    	<div class='form-group'>
      	<%= f.label :email %>
      	<%= f.email_field :email, class: 'form-control' %>
    	</div>
    	<div class='form-group'>
      	<%= f.label :password %>
      	<%= f.password_field :password, class: 'form-control' %>
    	</div>
    	<div class='form-group'>
      	<%= f.label :password_confirmation %>
      	<%= f.password_field :password_confirmation, class: 'form-control' %>
    	</div>
    	<%= f.submit 'Register', class: 'btn btn-primary form-control' %>
  <% end %>

  <p class='mt-2'>
    Already have an account? <%= link_to 'Click here to sign in.', login_path %>
  </p>
</div>