config/routes.rb
Rails.application.routes.draw do
  
  root 'articles#index'
  get 'welcome/index'
  resources :sessions, only: [:create]
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'users', to: 'users#index'
  patch '/users/:id', to: 'users#update', as: 'user_update'
  get '/confluence', to: 'confluences#index'
  get '/confluence/space', to: 'confluences#getspacelist'
  get 'confluence/page/:space_id', to: 'confluences#getspacepages', as: 'page'
  get 'confluence/children/:page_id', to: 'confluences#getchildpages', as: 'child'
  get 'confluence/content/:content_id', to: 'confluences#getviewcontent', as: 'pageview'
	
	resources :articles do
    resources :comments
  end

  resources :categories do
  end

	get 'categories/:category_id/articles', to: 'articles#showcategoryarticles', as: 'show_all'
  get 'blog/new', to: 'blog#new'
	post 'blog/new', to: 'blog#create'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :category
	has_many :comments, dependent: :destroy
	validates :title, 
		presence: true, 
		length: { minimum: 5 }, 
		uniqueness: true
end

app/models/bl.rb
class Bl < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles, dependent: :destroy
	validates :name, 
		presence: true, 
		length: { minimum: 5 }, 
		uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :email, uniqueness: true, presence: true
	enum role: [:guest, :editor, :admin]
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
		@category = Category.all
	end

	def edit
		@article = Article.find(params[:id])
		@category = Category.all
	end

	def create
		@article = Article.new(article_params)
		@category = Category.all
	 	if @article.save
	 		redirect_to @article
	 	else
	 		render 'new'
	 		# redirect_to action: "new" 
	 	end
	end

	def update 
		@article = Article.find(params[:id])
		# @category = Category.all
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
	    @article = Article.find(params[:id])
	    authorize @article
	    @article.destroy
	    redirect_to articles_path
  	end

  	def showcategoryarticles
  		@category = Category.find(params[:category_id])
 	end

	private
  		def article_params
    		params.require(:article).permit(:title, :text, :category_id)
  		end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
	def new
	end

	def create
		@blog = Bl.new(param_permission)

		@blog.save
		redirect_to @blog
	end
	private 
		def param_permission
			params.require(:blog).permit(:title, :text)
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@category = Category.all
	end

	def show
	end

	def new
		@category = Category.new
  	end

  	def edit
		@category = Category.find(params[:id])
	end

  	def create
  		@category = Category.new(category_params)

	 	if @category.save
	 		redirect_to action: "index"
	 	else
	 		render 'new'
	 	end
  	end

  	def update
		@category = Category.find(params[:id]);
		if @category.update(category_params)
			redirect_to action: "index"
		else
			render 'edit'
		end
	end

  	def destroy
  		@category = Category.find(params[:id])
	    @category.destroy
	    redirect_to action: "index"
  	end

  	private 
  		def category_params
  			params.require(:category).permit(:name)
  		end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	#http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
	    @comment = @article.comments.find(params[:id])
	    @comment.destroy
	    redirect_to article_path(@article)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_valid_user!, except: [:destroy]
	
  def new
	end

	def create
		reset_session
		@user = User.find_by(email: session_params[:email])
		
		if @user && @user.authenticate(session_params[:password])
			session[:user_id] = @user.id
      session[:user_email] = @user.email
			flash[:success] = 'welcome'
			redirect_to root_path
		else
			flash[:error] = 'Invalid email/password combination'
			redirect_to login_path
		end
	end

	def destroy
		reset_session
	end

	def session_params
		params.require(:session).permit(:email, :password)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	
    skip_before_action :require_valid_user!

    def index
      @users = User.all
      @enum = User.roles
      authorize @user
    end

  	def new
  		@user = User.new
  	end

  	def create
  		@user = User.new(user_params)

  		if@user.save
  			flash[:success] = 'new user is created'
  			redirect_to login_path
  		else
  			render :new
  		end
  	end

    def update
      @user = User.find(params[:id])
      # @category = Category.all
      # authorize @user
      if @user.update(user_params)
        redirect_to :action => 'index'
      else
        render 'edit'
      end
    end

  	def user_params
  		params.require(:user).permit(:email, :password, :password_confirmation, :role)  		
  	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/confluences_helper.rb
module ConfluencesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/edit.html.erb
<div class="container-form">
  	<div class="header">
    	<div class="header_title">
      		<h4>Edit category</h4>
    	</div>
  	</div>
  	<% if @category.errors.any? %>
    	<div id="error_explanation">
      		<h2>
        		<%= pluralize(@category.errors.count, "error") %> prohibited this article from being saved:
      		</h2>
	      	<ul>
	        	<% @category.errors.full_messages.each do |msg| %>
	          		<li><%= msg %></li>
	        	<% end %>
	      	</ul>
    	</div>
  	<% end %>
  	<%= form_for :category, url: category_path(@category), method: :patch do |f|%>
  		<p>
  			<%= f.label :name %><br>
   	 		<%= f.text_field :name, :class=>'input-box' %>
  		</p>
  		<p>
    		<%= f.submit :class=>"submit" %>
  		</p>
  	<% end %>
</div>

app/views/categories/index.html.erb
<div class="header">
	<div class="header_title">
		<h1>All Categories</h1>
	</div>
</div>
<button class="btn btn-new btn-primary"><%= link_to 'new category', new_category_path %></button>

<table class="category-list">
	<% @category.each do |category| %>
		<tr>
			<td class="s-right">
				<strong><%= link_to category.name , show_all_path(category) %></strong>
			</td>
			<td class="s-both">
				<button class="btn btn-warning btn-action">
					<%= link_to 'edit', edit_category_path(category)%>
				</button>
			</td>
			<td class="s-both">
				<button class="btn btn-danger btn-action">
					<%= link_to 'delete', category_path(category), method: :delete, data: { confirm: 'Are you sure to delete?' } %>
				</button>
			</td>
		</tr>
	<% end %>
</table>

app/views/categories/new.html.erb
<div class="container-form">
  <div class="header">
    <div class="header_title">
      <h1>Add category</h1>
    </div>
  </div>

  <%= form_for :category, url: categories_path do |f| %>
  <% if @category.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@category.errors.count, "error") %> prohibited
      this category from being saved:
    </h2>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, {:class=>'input-box'}%>
  </p>
  <p>
    <%= f.submit "save", :class=>"form-control submit" %>
  </p>
  <% end %>
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<h1>List of categories</h1>
<% @category.each do |category| %>
	<p><%=category.name%></p>
<% end %>